-- MySQL Script generated by MySQL Workbench
-- Fri Aug 16 09:39:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema locadora
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema locadora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `locadora` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `locadora` ;

-- -----------------------------------------------------
-- Table `locadora`.`filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`filme` (
  `id_filme` INT(11) NOT NULL,
  `diretor` VARCHAR(50) NULL DEFAULT NULL,
  `disponivel` INT(11) NULL DEFAULT NULL,
  `quantidade` INT(11) NULL DEFAULT NULL,
  `titulo` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_filme`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `locadora`.`hibernate_sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`hibernate_sequence` (
  `next_val` BIGINT(20) NULL DEFAULT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `locadora`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`user` (
  `user_id` INT(11) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `UK_2quavun5ve2gtfijnanbvhtj0` (`user_id` ASC, `name` ASC) VISIBLE,
  UNIQUE INDEX `id_email` (`user_id` ASC, `email` ASC) VISIBLE,
  UNIQUE INDEX `UK_ob8kqyqqgmefl0aco34akdtpe` (`email` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `locadora`.`locacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`locacao` (
  `codigo_locacao` INT(11) NOT NULL AUTO_INCREMENT,
  `data_devolucao` DATETIME NULL DEFAULT NULL,
  `data_emprestimo` DATETIME NULL DEFAULT NULL,
  `prazo_devolucao` DATETIME NULL DEFAULT NULL,
  `titulo` VARCHAR(255) NULL DEFAULT NULL,
  `user_name` VARCHAR(100) NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  `id_filme` INT(11) NOT NULL,
  PRIMARY KEY (`codigo_locacao`),
  INDEX `FKsy9awe8cduaottjmomj0ywq2e` (`user_name` ASC) VISIBLE,
  INDEX `fk_locacao_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_locacao_filme1_idx` (`id_filme` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `locadora`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`role` (
  `role_id` INT(11) NOT NULL,
  `role` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `locadora`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`user_role` (
  `user_id` INT(11) NULL,
  `role_id` INT(11) NOT NULL,
  `user_rolecol` VARCHAR(45) NULL,
  INDEX `fk_user_role_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_user_role_role1_idx` (`role_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
