-- MySQL Script generated by MySQL Workbench
-- Sun Aug 18 22:18:54 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema locadora
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema locadora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `locadora` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `locadora` ;

-- -----------------------------------------------------
-- Table `locadora`.`filme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `locadora`.`filme` ;

CREATE TABLE IF NOT EXISTS `locadora`.`filme` (
  `id_filme` INT(11) NOT NULL,
  `diretor` VARCHAR(50) NULL DEFAULT NULL,
  `disponivel` INT(11) NULL DEFAULT NULL,
  `quantidade` INT(11) NULL DEFAULT NULL,
  `titulo` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_filme`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `locadora`.`filme_seq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `locadora`.`filme_seq` ;

CREATE TABLE IF NOT EXISTS `locadora`.`filme_seq` (
  `next_val` BIGINT(20) NOT NULL,
  PRIMARY KEY (`next_val`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;




-- -----------------------------------------------------
-- Table `locadora`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `locadora`.`user` ;

CREATE TABLE IF NOT EXISTS `locadora`.`user` (
  `user_id` INT(11) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `UK_2quavun5ve2gtfijnanbvhtj0` (`user_id` ASC, `name` ASC) VISIBLE,
  UNIQUE INDEX `id_email` (`user_id` ASC, `email` ASC) VISIBLE,
  UNIQUE INDEX `UK_ob8kqyqqgmefl0aco34akdtpe` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `locadora`.`user_seq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `locadora`.`user_seq` ;

CREATE TABLE IF NOT EXISTS `locadora`.`user_seq` (
  `next_val` BIGINT(20) NOT NULL,
  PRIMARY KEY (`next_val`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;




-- -----------------------------------------------------
-- Table `locadora`.`locacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `locadora`.`locacao` ;

CREATE TABLE IF NOT EXISTS `locadora`.`locacao` (
  `codigo_locacao` INT(11) NOT NULL AUTO_INCREMENT,
  `data_devolucao` DATETIME NULL DEFAULT NULL,
  `data_emprestimo` DATETIME NULL DEFAULT NULL,
  `prazo_devolucao` DATETIME NULL DEFAULT NULL,
  `titulo` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  `id_filme` INT(11) NOT NULL,
  PRIMARY KEY (`codigo_locacao`),
  INDEX `FK_USER` (`name` ASC) VISIBLE,
  INDEX `fk_locacao_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_locacao_filme1_idx` (`id_filme` ASC) VISIBLE,
  CONSTRAINT `fk_locacao_filme1`
    FOREIGN KEY (`id_filme`)
    REFERENCES `locadora`.`filme` (`id_filme`),
  CONSTRAINT `fk_locacao_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `locadora`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `locadora`.`locacao_seq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `locadora`.`locacao_seq` ;

CREATE TABLE IF NOT EXISTS `locadora`.`locacao_seq` (
  `next_val` BIGINT(20) NOT NULL,
  PRIMARY KEY (`next_val`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `locadora`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `locadora`.`role` ;

CREATE TABLE IF NOT EXISTS `locadora`.`role` (
  `role_id` INT(11) NOT NULL,
  `role` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `locadora`.`role_seq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `locadora`.`role_seq` ;

CREATE TABLE IF NOT EXISTS `locadora`.`role_seq` (
  `next_val` BIGINT(20) NOT NULL,
  PRIMARY KEY (`next_val`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `locadora`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `locadora`.`user_role` ;

CREATE TABLE IF NOT EXISTS `locadora`.`user_role` (
  `user_id` INT(11) NOT NULL,
  `role_id` INT(11) NOT NULL,
  UNIQUE INDEX `UK_it77eq964jhfqtu54081ebtio` (`role_id` ASC) VISIBLE,
  INDEX `fk_user_role_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_user_role_role1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `locadora`.`role` (`role_id`),
  CONSTRAINT `fk_user_role_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `locadora`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
 

INSERT INTO locadora.user
VALUES (1,"admin@admin.com","admin","$2a$10$kWAAmR5/Wn/TC6Ez3gFmJOzICkgaWG/5egMLSbR6vVJCH3uchkwmq");

INSERT INTO locadora.role
VALUES (1,"ADMIN");

INSERT INTO locadora.user_role
VALUES (1,1);

INSERT INTO locadora.user_seq
VALUES (2);

INSERT INTO locadora.role_seq
VALUES (2);



